### ISSUE TITLE
Bug in stress

### ISSUE THREAD

**Issue by bonfus** [fspiga/qe-gpu#34]
### Version of QE-GPU

Release 1.0 on github.

    $ md5sum qe-gpu-1.0.tar.gz 
    ee6f2df9b1989ec9f1aee9a9066784ed  qe-gpu-1.0.tar.gz

### Expected behavior/result

Pressure agrees with CPU version of the code or information about missing features in the GPU code are reported.

### Actual behavior/result

The simulation ends, energies are fine, pressure is wrong.

### Comparison of outputs:

GPU: 

     the Fermi energy is    15.3088 ev

    !    total energy              =     -85.72339901 Ry
     Harris-Foulkes estimate   =     -85.72339901 Ry
     estimated scf accuracy    <          6.3E-11 Ry

     The total energy is the sum of the following terms:

     one-electron contribution =       0.30223721 Ry
     hartree contribution      =      14.33673853 Ry
     xc contribution           =     -29.60837116 Ry
     ewald contribution        =     -70.75404435 Ry
     smearing contrib. (-TS)   =       0.00004076 Ry

     total magnetization       =     0.73 Bohr mag/cell
     absolute magnetization    =     0.78 Bohr mag/cell

     convergence has been achieved in  12 iterations

     Computing stress (Cartesian axis) and pressure

          total   stress  (Ry/bohr**3)                   (kbar)     P=   81.48
       0.00055386   0.00000000  -0.00000000         81.48      0.00     -0.00
       0.00000000   0.00055386  -0.00000000          0.00     81.48     -0.00
      -0.00000000   0.00000000   0.00055386         -0.00      0.00     81.48

CPU:

     the Fermi energy is    15.3088 ev

    !    total energy              =     -85.72339901 Ry
     Harris-Foulkes estimate   =     -85.72339901 Ry
     estimated scf accuracy    <          6.3E-11 Ry

     The total energy is the sum of the following terms:

     one-electron contribution =       0.30223721 Ry
     hartree contribution      =      14.33673853 Ry
     xc contribution           =     -29.60837116 Ry
     ewald contribution        =     -70.75404435 Ry
     smearing contrib. (-TS)   =       0.00004076 Ry

     total magnetization       =     0.73 Bohr mag/cell
     absolute magnetization    =     0.78 Bohr mag/cell

     convergence has been achieved in  12 iterations

     entering subroutine stress ...

          total   stress  (Ry/bohr**3)                   (kbar)     P=  -14.96
      -0.00010170  -0.00000000   0.00000000        -14.96     -0.00      0.00
      -0.00000000  -0.00010170  -0.00000000         -0.00    -14.96     -0.00
       0.00000000  -0.00000000  -0.00010170          0.00     -0.00    -14.96

### Steps to reproduce behavior/result

Use the input files in [stress.tar.gz](https://github.com/fspiga/qe-gpu/files/1686647/stress.tar.gz)

instructions how to reproduce the problem:
* Machine: GALILEO@CINECA (x86)
* type of GPU: K80 Driver Version: 375.39, CUDA Toolkit 8.0
* Open MPI shipped with PGI Compiler
* PGI compiler 17.10

* the full ``DFLAGS`` line as specified in the make.inc:
 
    DFLAGS         = -DUSE_CUDA -D__FFTW -D__MPI -D__MKL

* how you run the code (number of MPI/GPU, number of threads)

     mpirun -np 1 pw.x -inp input_file

**Comment by romerojosh** [comment]
Thanks for reporting this bug. It was an issue in the local stress computation where the wrong mesh variable was being used. This has been fixed with commit 1a4e14d.

GPU output is now consistent with CPU output for the provided test case:
```
     the Fermi energy is    15.3088 ev

!    total energy              =     -85.72339901 Ry
     Harris-Foulkes estimate   =     -85.72339901 Ry
     estimated scf accuracy    <          6.3E-11 Ry

     The total energy is the sum of the following terms:

     one-electron contribution =       0.30223721 Ry
     hartree contribution      =      14.33673853 Ry
     xc contribution           =     -29.60837116 Ry
     ewald contribution        =     -70.75404435 Ry
     smearing contrib. (-TS)   =       0.00004076 Ry

     total magnetization       =     0.73 Bohr mag/cell
     absolute magnetization    =     0.78 Bohr mag/cell

     convergence has been achieved in  12 iterations


     Computing stress (Cartesian axis) and pressure

          total   stress  (Ry/bohr**3)                   (kbar)     P=  -14.96
  -0.00010170  -0.00000000  -0.00000000        -14.96     -0.00     -0.00
  -0.00000000  -0.00010170   0.00000000         -0.00    -14.96      0.00
  -0.00000000   0.00000000  -0.00010170         -0.00      0.00    -14.96
```
